#!/usr/bin/python
import os

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv,
											'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
	execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
	pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path

# Import from parent directory
parentdir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.sys.path.insert(0, parentdir)
import ofCodeStyleGuard

# Instantiate a PrHandler, which start waiting on styleguard.MY_QUEUE
_threaded_pr_worker = ofCodeStyleGuard.styleguard.PrHandler()
#APP.run(host='0.0.0.0', port=styleguard.cfg['local_port'])
application = ofCodeStyleGuard.APP
ofCodeStyleGuard.styleguard.MY_QUEUE.join()
